version: "3"

services:
  actionhero:
    environment:
      REDIS_HOST: redis
    build:
      context: ./phishpi.nodejs
#      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - "redis"
  redis:
    image: "redis:alpine"