name: Unit Tests

on: [push]

jobs:
  platformio:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run platformio test
      run: platformio test --project-dir phishpi.arduino/ -e native
  node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.19.0]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: ls -l;pwd
#    - run: npm install --save-dev jest
#      working-directory: phishpi.node.js
    - run: node_modules/.bin/jest
      working-directory: phishpi.node.js
